// flow-typed signature: 5197dfcb9efcfe2b3a23a308898d9b45
// flow-typed version: <<STUB>>/sb-communication_v5.0.0/flow_v0.71.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'sb-communication'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'sb-communication' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'sb-communication/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'sb-communication/lib/index.js' {
  declare module.exports: $Exports<'sb-communication/lib/index'>;
}
